### ISSUE TITLE
Please consider fixing STM32F303ZE model RAM size.

### ISSUE THREAD

**Issue by Cooler1989** [embassy-rs/stm32-data-generated#1]
Quite old but a 'flagship' of STM discovery board STM32F303DISCOVERY cann't be tested and used because wrong RAM size makes execution  go to hardfault handling loop. There is no easy way to diagnose without debugger. Size is defined as 64kB where 48kB are available.

**Comment by adamgreig** [comment]
What chip do you have? All STM32F303xD/E have 64kB RAM by definition, I thought. The `xC` chips have 48kB, but if you have one of those, you should be able to select the `stm32f303cb` feature (etc). In any event this is the repo, check out https://github.com/embassy-rs/stm32-data.

**Comment by Dirbaio** [comment]
closing in favor of https://github.com/embassy-rs/stm32-data/issues/301
